title:              Seihoon's Blog
email:              yuiyt@korea.ac.kr
description:        Thinking Factory
author:             Seihoon
baseurl:            ""
url:                "https://seihoon0111.github.io"

# Social Profiles
twitter_username:  
github_username:    seihoon0111
facebook_username:  
instagram_username: seihoon_0.0 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
